### ISSUE TITLE
some files in win32 folder patch failed.

### ISSUE THREAD

**Issue by mikuyourworld** [HybridEidolon/pso2-modpatcher#1]
I found those four files can not be patched right.

_08d0a310335deb792477bd14e4c73c7e
ad26a5e8cc0e2e14f2709a3d07a6ea94
bedfcb62d45a4694e9276376e3801594
caf5e6b88f20cab4c8ee7298c812642e_

Although they are patched seems like sucessed, but the game can not load them, so when you try to get into pso2, you will be in loading scrren forever. And if you try to unpack them you will get nothing for 08d0a310335deb792477bd14e4c73c7e, even a empty folder. left 3 will give you 3 empty folders.

The link is the file I used to patch them.

https://mega.nz/file/QAoRFQbK#h19fw7EzKac6i93P7JYNkGPV_FvXDx2dsb4yDoBIpLs

**Comment by HybridEidolon** [comment]
Sure enough, they _appear_ to patch correctly in the tool too, but result in a loading tunnel or frozen black screen when used, and the output files can't be unpacked. Sounds like there's a bug in my ICE writing code.

**Comment by HybridEidolon** [comment]
To elaborate: the issue was that, groups under a certain size threshold need to be encrypted in two passes. However, the threshold is different depending on the ICE "version". But the writer code would always use the wrong threshold for "v4" archives, thus, if a group fit between the smaller threshold and the larger threshold, it would be inappropriately two-pass encrypted when it should only have been one pass. This is important because decryption uses the size of the group to determine whether to one or two-pass _decrypt_, meaning that readers would get garbage data when attempting to decrypt it.
